spring.application.name=corebanking


# Database Connection Settings


spring.datasource.url=jdbc:mysql://42.156.32.114:4405
spring.datasource.username=cbd_g1_2
spring.datasource.password=cbdg12

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Settings
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Configuration
jwt.secret=Y29yZWJhbmtpbmctand0LXNlY3JldC1rZXktMjAyNi1wcm9kdWN0aW9uLWdyYWRl
jwt.expiration=3600000
jwt.issuer=corebanking

