spring.application.name=corebanking


# Database Connection Settings
spring.datasource.url=jdbc:mysql://42.156.32.114:4405/cbd
spring.datasource.username=cbd_g3_4
spring.datasource.password=cbdg34
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
t
# JPA/Hibernate Settings
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Configuration
jwt.secret=Y29yZWJhbmtpbmctand0LXNlY3JldC1rZXktMjAyNi1wcm9kdWN0aW9uLWdyYWRl
jwt.expiration=3600000
jwt.issuer=corebanking

jasper.report.path=classpath:reports/


spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=khinzarchithein29@gmail.com
spring.mail.password=sqvoxrhzrnybxsfw


spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true